identifier: l2w9z1g748i8916a
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: D:\GitHub\AngularProjectsBook\Capitulo2\my-blog
distFolder: dist/my-blog
outDir: D:\GitHub\AngularProjectsBook\Capitulo2\my-blog\dist\static
handle404: ''
